CREATE TABLE TransactionsPin (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Pin VARCHAR(50) NOT NULL,
    Attemp INT NOT NULL,
    Blocked BOOL NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME
);